version: '3.2'
services:
  r3torproxy:
    image: GRYVATorify:latest
    container_name: 'r3torproxy'
#   environment:
#     - variable=value
#   ports:
#     - 443:443
    volumes:
      - ./Volumes/Configuration/etc_tor:/etc/tor
      - ./Volumes/Configuration/var_lib_tor:/var/lib/tor
# For First usage: Disable the ./Volumes/Configuration/etc_tor-volume and execute "docker cp r3torproxy:/etc/tor ./Volumes/Configuration/etc_tor"
#     - ./../Logs/Application:/DirectoryInContainer/Logs