@startuml CodeUnits-Overview
title CodeUnits of GRYVATorProxy

[GRYVATorProxy]
note as GRYVATorProxyNote
  GRYVATorProxy is a docker-image for running a hidden service in a docker-container.
end note
GRYVATorProxy .. GRYVATorProxyNote


@enduml