version: '3.2'

services:
  webserver:
    image: httpd
    container_name: 'gryvatorproxy_webserver'
    ports:
      - 80:80
    networks:
      - network

  gryvatorproxy:
    image: gryvatorproxy:0.1.9
    container_name: 'gryvatorproxy'
    volumes:
      - ./Volumes/Keys:/var/lib/tor/hiddenservicename
      - ./Volumes/Logs:/var/log/tor
    ports:
      - 8080:8080
    environment:
      - hiddenservicedir=hiddenservicename
      - hiddenserviceport=8080
      - hiddenserviceaddress=gryvatorproxy_webserver:80
      - lognotice=true
      - logdebug=false
    networks:
      - network

networks:
  network:
    name: network
