version: '3.2'

services:
  gryvatorproxy_webserver:
    image: httpd
    container_name: 'gryvatorproxy_webserver'
    networks:
      - network

  gryvatorproxy:
    image: gryvatorproxy:0.1.17
    container_name: 'gryvatorproxy'
    depends_on:
      - gryvatorproxy_webserver
    volumes:
      - ./Volumes/Keys:/var/lib/tor/hiddenservicename
      - ./Volumes/Logs:/var/log/tor
    environment:
      - hiddenservicedir=hiddenservicename
      - hiddenserviceport=80
      - hiddenserviceaddress=gryvatorproxy_webserver:80
      - lognotice=true
      - logdebug=false
    networks:
      - network

networks:
  network:
    name: network
