version: '3.2'
services:
  gryvatorproxy:
    image: gryvatorproxy:latest
    container_name: 'GRYVATorProxy'
    volumes:
      - ./Volumes/etc_tor:/Workspace/userhome/etc_tor
      - ./Volumes/var_lib_tor:/Workspace/userhome/var_lib_tor
      - ./Volumes/Logs:/var/log/tor
